{{- range .Values.persistentVolumeClaims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessMode  }}
  resources:
    requests:
      storage: {{ .size  }}
  storageClassName: {{ .storageClass  }}
---
{{- end }}