apiVersion: v1
items:
- apiVersion: networking.istio.io/v1
  kind: Gateway
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.istio.io/v1","kind":"Gateway","metadata":{"annotations":{},"creationTimestamp":"2024-08-16T21:30:30Z","generation":2,"name":"hello-world-gateway","namespace":"external-dns","resourceVersion":"43643","uid":"aa8c5d2b-63cd-4dd4-9f43-4fe51b95b94e"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["hello-world.rmikl.pl"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
    creationTimestamp: "2024-08-16T22:51:01Z"
    generation: 1
    name: hello-world-gateway
    namespace: external-dns
    resourceVersion: "50101"
    uid: 06429eaa-4e3e-4204-8632-3c431ebfa452
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - hello-world.rmikl.pl
      port:
        name: http
        number: 80
        protocol: HTTP
kind: List
metadata:
  resourceVersion: ""
