server:
  ingress:
    enabled: false  

  service:
    type: ClusterIP 
    annotations: {}
    name: argocd
  extraArgs:
    - --insecure

  rbac:
    enabled: true
    policy:
      default: role:readonly

  config:
    url: https://argo.rmikl.pl

crd:
  install: true
redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false