provider: azure

azure:
  resourceGroup: "${RESOURCE_GROUP}"
  subscriptionId: "${SUBSCRIPTION_ID}"  
  tenantId: "${TENANT_ID}"
  secretName: azure-credentials

domainFilters:
  - rmikl.pl

txtOwnerId: externaldns
namespace: default
logLevel: info
replicaCount: 1
resources: {}

#extraVolumes:
#- name: azure-credentials
#  secret:
#    secretName: azure-credentials
#
#extraVolumeMounts:
#- name: azure-credentials
#  mountPath: /etc/kubernetes/azure.json
#  subPath: azure.json
#  readOnly: true