provider: azure

azure:
  resourceGroup: "${RESOURCE_GROUP}"
  subscriptionId: "${SUBSCRIPTION_ID}"  
  tenantId: "${TENANT_ID}"
  secretName: azure-credentials

domainFilters:
  - rmikl.pl

txtOwnerId: externaldns
namespace: external-dns
logLevel: debug
replicaCount: 1
resources: {}

sources:
- service
- ingress
- istio-gateway
- istio-virtualservice

polucy: sync
registry: txt

rbac:
  create: true
  serviceAccountName: external-dns

annotationFilter: "external-dns.alpha.kubernetes.io/hostname"

