apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  type: {{ .Values.guacamole.service.type }}
  selector:
    app: guacamole
  ports:
  - protocol: TCP
    port: {{ .Values.guacamole.service.port }}
    targetPort: 8080