apiVersion: v1
kind: Service
metadata:
  name: {{ include "vnc.fullname" . }}
  labels:
    {{- include "vnc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 80
      nodePort: {{ .Values.service.httpNodePort }}