apiVersion: v1
kind: Service
metadata:
  name: {{ include "vnc.fullname" . }}
  labels:
    {{- include "vnc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    matchLabels:
{{ include "vnc.selectorLabels" . | indent 6 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 80
      nodePort: {{ .Values.service.httpNodePort }}