apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: ovpn-proxy
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: ovpn-proxy
  template:
    metadata:
      labels:
        app: ovpn-proxy
    spec:
      dnsConfig:
        nameservers:
{{ toYaml .Values.deployment.dnsConfig.nameservers | indent 8 }}
      containers:
        - name: ovpn-proxy
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          resources:
            limits:
              memory: "{{ .Values.deployment.resources.limits.memory }}"
              cpu: "{{ .Values.deployment.resources.limits.cpu }}"
            requests:
              memory: "{{ .Values.deployment.resources.requests.memory }}"
              cpu: "{{ .Values.deployment.resources.requests.cpu }}"
          env:
            - name: LOCAL_NETWORK
              value: "{{ .Values.deployment.env.LOCAL_NETWORK }}"
            - name: OPENVPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ovpn-proxy-secret
                  key: OPENVPN_USERNAME
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ovpn-proxy-secret
                  key: OPENVPN_PASSWORD
          volumeMounts:
            - mountPath: /config/config.ovpn
              name: config-volume
              subPath: config.ovpn
            - mountPath: /dev/net/tun
              name: tun-device
              readOnly: true
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        - name: config-volume
          secret:
            secretName: ovpn-proxy-secret
        - name: tun-device
          hostPath:
            path: /dev/net/tun
            type: CharDevice
