apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.pod.namespace }}
spec:
  selector:
    app: ovpn-proxy
  ports:
{{- range .Values.service.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
{{- end }}
  type: {{ .Values.service.type }}