apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.ipAddressPool.namespace }}
spec:
  {{- if .Values.ipAddressPool.addresses }}
  addresses:
    {{- range .Values.ipAddressPool.addresses }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}