trigger:
- none

pr:
- none

parameters:
- name: azureCredentials
  type: string
  default: 'AZURE_SC'

- name: environment
  type: string
  default: 'dev-1'

- name: helmOperation
  type: string
  default: 'apply'
  values:
    - destroy
    - apply

- name: project
  type: string
  default: 'rmikl' 

- name: aksResourceGroup
  type: string
  default: 'rmikl-dev-1'

variables:
  - group: local


stages:
- stage: HELMFILE_APPLY
  displayName: 'Helmfile ${{ parameters.helmOperation }}'
  jobs:
  - job:
    displayName: 'Helm ${{ parameters.helmOperation }}'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Helm ${{ parameters.helmOperation }}'
      inputs:
        azureSubscription: ${{ parameters.azureCredentials }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          #####prepare agent for helmfile        
          helm plugin install https://github.com/databus23/helm-diff
          sudo apt update
          sudo apt-get install build-essential -y
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install helmfile
          envsubst --version
          #####get kubeconfig
          az aks get-credentials --resource-group ${{ parameters.aksResourceGroup }} --name ${{ parameters.environment }}-${{ parameters.project }}

          #####prepare helmfile values files
          input_dir=helmfile/${{ parameters.environment }}/helm-values-templates
          output_dir=helmfile/${{ parameters.environment }}/helm-values
          mkdir $output_dir -p
          for file in "$input_dir"/*.yaml; do
            filename=$(basename "$file" .yaml)
            envsubst < "$file" > "${output_dir}/${filename}-${{ parameters.environment }}.yaml"
          done

          #####helmfile operation
          tree .
      env:
          CLIENT_ID: $(armClientId)
          CLIENT_SECRET: $(armClientSecret)
          TENANT_ID: $(armTenantId)
          SUBSCRIPTION_ID: $(armSubscriptionId)
          RESOURCE_GROUP: ${{ parameters.project }}