secretStore:
  name: doppler-auth-api
  doppler:
    dopplerTokenSecretName: doppler-token-auth-api
    dopplerTokenKey: dopplerToken
  
externalSecret:
  name: auth-api-db-url
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api
  targetSecretName: auth-api-db-url
  namespacesToCopy: "media"
  data:
    - secretKey: CF_API_TOKEN
      remoteRefKey: CF_API_TOKEN