apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-externalsecret
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: "{{ .Values.refreshInterval }}"
  secretStoreRef:
    name: {{ include "external-secrets-chart.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: "{{ .Values.targetSecretName }}"
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        azure.json: |
          {
            "tenantId": "{{ "{{ toString .tenantId }}" }}",
            "subscriptionId": "{{ "{{ toString .subscriptionId }}" }}",
            "resourceGroup": "{{ "{{ toString .resourceGroup }}" }}",
            "useManagedIdentityExtension": true,
            "userAssignedIdentityID": "{{ "{{ toString .userAssignedIdentityId }}" }}"
          }
  data:
  - secretKey: tenantId
    remoteRef:
      key: {{ .Values.tenantIdSecretRef }}
  - secretKey: subscriptionId
    remoteRef:
      key: {{ .Values.subscriptionIdSecretRef }}
  - secretKey: resourceGroup
    remoteRef:
      key: {{ .Values.resourceGroupSecretRef }}
  - secretKey: userAssignedIdentityId
    remoteRef:
      key: {{ .Values.userAssignedIdentityIDsecretRef }}
