apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-externalsecret
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: "{{ .Values.refreshInterval }}"
  secretStoreRef:
    name: {{ include "external-secrets-chart.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: "{{ .Values.targetSecretName }}"
    creationPolicy: Owner
  template:  
    data:
      azure.json: |
        {
          "tenantId": "{{ .Data.tenantId }}"
        }
  data:
  - secretKey: ${{ .Values.tenantIdSecretRef }}
    remoteRef:
      key: tenantId
