apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-externalsecret
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: "{{ .Values.refreshInterval }}"
  secretStoreRef:
    name: {{ include "external-secrets-chart.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: "{{ .Values.targetSecretName }}"
    creationPolicy: Owner
  data:
    - secretKey: "azure.json"  
      remoteRef:
        key: "{{ .Values.tenantIdSecretRef }}"  
  template:  
    data:
      azure.json: |
        {
          "tenantId": "{{ .data.tenantId }}"
        }
