apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-externalsecret
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: "{{ .Values.refreshInterval }}"
  secretStoreRef:
    name: {{ include "external-secrets-chart.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: "{{ .Values.targetSecretName }}"
    creationPolicy: Owner
  #template:
  #  type: Opaque
  #  data:
  #    azure.json: |
  #    {
  #      tenantId: "{{ .tenantId }}"
  #    }
  data:
  - secretKey: tenantId
    remoteRef:
      key: tenantId
