apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-secretstore
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: "managedIdentity"
      vaultUrl: "{{ .Values.azure.vaultUrl }}"
      managedIdentity:
        clientID: "{{ .Values.azure.managedIdentityClientID }}"