apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "external-secrets-chart.fullname" . }}-secretstore
  labels:
    {{- include "external-secrets-chart.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: "{{ .Values.azure.vaultUrl }}"
      identityId: "{{ .Values.azure.managedIdentityClientID }}"