apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dlink
provisioner: smb.csi.k8s.io
parameters:
  source: //192.168.1.22/Volume_1
  csi.storage.k8s.io/provisioner-secret-name: dlink-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: cluster-operators
  csi.storage.k8s.io/node-stage-secret-name: dlink-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: cluster-operators
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - vers=1.0
  - rsize=1048576
  - wsize=1048576
  - noperm
  - noacl