{{- range .Values.certificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .certificate.issuer }}-{{ .name }}
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .namespacesToCopy | quote }}
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ .namespacesToCopy | quote }}
  secretName: {{ .certificate.issuer }}-{{ .name }}-tls
  issuerRef:
    name: {{ .certificate.issuer }}
    kind: ClusterIssuer
  commonName: {{ .commonName }}
  dnsNames:
    {{- range .dnsNames }}
    - {{ . | quote }}
    {{- end }}
---
{{- end }}