apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: robert.miklas@protonmail.com  # Replace with your email
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azureDNS:
          subscriptionID: {{ .Values.clusterIssuer.subscriptionIdRef }}
          resourceGroupName: {{ .Values.clusterIssuer.resourceGroupSecretRef }}
          hostedZoneName: {{ .Values.clusterIssuer.dnsZoneSecretRef }}
          environment: AzurePublicCloud 
          managedIdentity:
            clientID: {{ .Values.clusterIssuer.managedIdentityClientID }}
