{{- range .Values.domains }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .gatewayName }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: {{ .hosts }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts: {{ .hosts }}
      tls:
        mode: SIMPLE
        credentialName: {{ .certificate.issuer }}-{{ .name }}
---
{{- end }}