{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- range $key, $value := .Values.gateway.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  servers:
  - port:
      number: {{ .Values.gateway.port.number }}
      name: {{ .Values.gateway.port.name | quote }}
      protocol: {{ .Values.gateway.port.protocol | quote }}
    hosts:
      {{- range .Values.gateway.hosts }}
      - {{ . | quote }}
      {{- end }}
    {{- if .Values.gateway.tls.enabled }}
    tls:
      mode: {{ .Values.gateway.tls.mode | quote }}
      credentialName: {{ .Values.gateway.tls.credentialName | quote }}
      {{- if .Values.gateway.tls.minProtocolVersion }}
      minProtocolVersion: {{ .Values.gateway.tls.minProtocolVersion | quote }}
      {{- end }}
      {{- if .Values.gateway.tls.maxProtocolVersion }}
      maxProtocolVersion: {{ .Values.gateway.tls.maxProtocolVersion | quote }}
      httpsRedirect: true
      {{- end }}
    {{- end }}
{{- end }}