{{- range .Values.domains }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
  name: {{ .gatewayName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts: 
      {{- toYaml .hosts | nindent 8 }}
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts: 
      {{- toYaml .hosts | nindent 8 }}
      tls:
        mode: SIMPLE
        credentialName: {{ printf "%s-%s-tls" .certificate.issuer .name }}
        minProtocolVersion: TLSV1_2
        maxProtocolVersion: TLSV1_3
---
{{- end }}