{{- if .Values.gateway.enabled }}
{{- range .Values.virtualServices }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app.kubernetes.io/instance: istio-networking
spec:
  hosts:
    - {{ .host | quote }}
  gateways:
    - {{ .gateway }}
  http:
    - match:
        - uri:
            port: {{ .matchPort }}
            prefix: /
      route:
        - destination:
            host: {{ .serviceName | quote }}
            port:
              number: {{ .servicePort }}
{{- end }}
{{- end }}
