{{- if .Values.gateway.enabled }}
{{- range .Values.virtualServices }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  hosts:
    - {{ .host | quote }}
  gateways:
    - {{ .gateway }}
  http:
    {{- if .tls.enabled }}
    - match:
        - port: 443
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .serviceName | quote }}
            port:
              number: {{ .servicePort }}
      tls:
        mode: SIMPLE
        credentialName: {{ .tls.credentialName | quote }}
        sniHosts:
          - {{ .host | quote }}
    {{- else }}
    - match:
        - port: 80
          uri:
            prefix: /
      route:
        - destination:
            host: {{ .serviceName | quote }}
            port:
              number: {{ .servicePort }}
    {{- end }}
{{- end }}
{{- end }}