apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    app: {{ include "qbittorrent.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "qbittorrent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent.name" . }}
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            limits:
              memory: "4Gi"
          ports:
            - containerPort: {{ .Values.service.webuiPort }}
              name: webui-port
            - containerPort: {{ .Values.service.torrentingPort }}
              name: torrent-port
            - containerPort: {{ .Values.service.torrentingPort }}
              protocol: UDP
              name: torrent-udp
          command: 
            - /bin/bash
            - -c
            - | 
                apk add --no-cache openssl
                # Input your new password here
                password="password"
                # Generate a random salt (16 bytes)
                salt=$(openssl rand -base64 16)
                # Number of iterations (adjust as needed for security)
                iterations=100000
                # Generate the PBKDF2 hash using openssl
                derived_key=$(openssl enc -aes-256-cbc -k "$password" -P -md md5 -nosalt -iter $iterations -base64 <<< "$salt")
                # Format the output
                password_pbkdf2="@ByteArray(newSalt:newHash)"
                echo "$password_pbkdf2"
                sed -i.bak "s|WebUI\\Password_PBKDF2=\".*\"|WebUI\\Password_PBKDF2=\"$password_pbkdf2\"|" /config/qBittorrent/qBittorrent.conf
                # Start qBittorrent
                /init

          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: WEBUI_PORT
              value: "{{ .Values.env.WEBUI_PORT }}"
            - name: TORRENTING_PORT
              value: "{{ .Values.env.TORRENTING_PORT }}"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: {{ .Values.persistence.config.subPath | quote }}
            - name: downloads-volume
              mountPath: /downloads
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: qbittorrent-downloads-pvc

