apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    app: {{ include "qbittorrent.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "qbittorrent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "qbittorrent.name" . }}
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.webuiPort }}
              name: webui-port
            - containerPort: {{ .Values.service.torrentingPort }}
              name: torrent-port
            - containerPort: {{ .Values.service.torrentingPort }}
              protocol: UDP
              name: torrent-udp
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: WEBUI_PORT
              value: "{{ .Values.env.WEBUI_PORT }}"
            - name: TORRENTING_PORT
              value: "{{ .Values.env.TORRENTING_PORT }}"
          volumeMounts:
            - name: config-volume
              mountPath: /config
              subPath: {{ .Values.persistence.config.subPath | quote }}  # Added subPath
            - name: downloads-volume
              mountPath: /downloads
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ include "qbittorrent.fullname" . }}-config-pvc
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: {{ include "qbittorrent.fullname" . }}-downloads-pvc
