apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    app: {{ include "qbittorrent.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "qbittorrent.name" . }}
  ports:
    - name: webui-port
      protocol: TCP
      port: {{ .Values.service.webuiPort }}
      targetPort: {{ .Values.service.webuiPort }}
      nodePort: {{ .Values.service.nodePort.webui }}
    - name: torrent-port
      protocol: TCP
      port: {{ .Values.service.torrentingPort }}
      targetPort: {{ .Values.service.torrentingPort }}
      nodePort: {{ .Values.service.nodePort.torrent }}
    - name: torrent-udp
      protocol: UDP
      port: {{ .Values.service.torrentingPort }}
      targetPort: {{ .Values.service.torrentingPort }}
      nodePort: {{ .Values.service.nodePort.torrent }}