apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: {{ .Values.service.type }}
  selector:
    app: qbittorrent
  ports:
  - protocol: TCP
    port: {{ .Values.service.webuiPort }}
    targetPort: {{ .Values.service.webuiPort }}
    nodePort: {{ .Values.service.nodePort.webui }}
  - protocol: TCP
    port: {{ .Values.service.torrentingPort }}
    targetPort: {{ .Values.service.torrentingPort }}
    nodePort: {{ .Values.service.nodePort.torrent }}
  - protocol: UDP
    port: {{ .Values.service.torrentingPort }}
    targetPort: {{ .Values.service.torrentingPort }}
    nodePort: {{ .Values.service.nodePort.torrent }}