replicaCount: 1

image:
  repository: elestio/docker-desktop-vnc
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  httpPort: 80
  httpNodePort: 30080

existingSecret: "docker-desktop-vnc-secret"

vncServer:
  serviceAccount:
    name: vnc-admin

env:
  USER: "rmikl"
