apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
spec:
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}

  target:
    name: {{ .Values.externalSecret.targetSecretName }}

  data:
    - secretKey: {{ .Values.externalSecret.data[0].secretKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data[0].remoteRefKey }}