apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.secretStore.doppler.dopplerTokenSecretName }}
            key: {{ .Values.secretStore.doppler.dopplerTokenKey }}