replicaCount: 1

image:
  repository: elestio/docker-desktop-vnc
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  httpPort: 80
  httpNodePort: 30081

env:
  USER: "rmikl"
  RESOLUTION: "1920x1080"

persistence:
  enabled: true
  storageClass: qnap
  size: 10Gi
