
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: embrerstack
  url: https://emberstack.github.io/helm-charts
- name: istio
  url: https://istio-release.storage.googleapis.com/charts
- name: softonic
  url: https://charts.softonic.io
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: reflector 
  namespace: kube-system
  chart: embrerstack/reflector
  version: 7.1.288

- name: istio-base
  namespace: istio-system
  chart: istio/base
  version: 1.23.0 
  values: []

- name: istiod
  namespace: istio-system
  chart: istio/istiod
  version: 1.23.0
  values: []

- name: istio-ingress
  namespace: istio-system
  chart: istio/gateway
  version: 1.23.0
  values: []
  hooks:
  - events: ["Wait for Istio Ingress Gateway to be ready"]
    command: sh
    args:
    - -c
    - |
      sleep 30

- name: predeploy-external-dns
  namespace: external-dns
  chart: ../../custom-charts/predeploy-external-dns
  version: 0.1.0
  values:
  - ./helm-values/predeploy-external-dns-dev-1.yaml

- name: argocd
  namespace: argocd
  chart: argo/argo-cd
  version: 7.4.4
  values:
  - ./helm-values/argo-dev-1.yaml

- name: external-dns
  namespace: external-dns
  chart: bitnami/external-dns
  version: 8.3.5
  values:
  - ./helm-values/external-dns-dev-1.yaml

- name: istio-networking
  namespace: istio-system
  chart: ../../custom-charts/istio-networking
  version: 0.1.0
  values:
  - ./helm-values/istio-networking-dev-1.yaml


