apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vnc.fullname" . }}
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "vnc.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "vnc.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.vncServer.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 3000
          env:
          - name: DRINODE
            value: "/dev/dri/renderD128"
          - name: CUSTOM_USER
            value: "{{ .Values.env.USER }}"
          - name: USER
            value: "{{ .Values.env.USER }}"
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: VNC_PASSWORD
          - name: GITHUB_TOKEN_RAW
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: GITHUB_TOKEN_RAW
          - name: LOCAL_NODES_PWD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingSecret }}
                key: LOCAL_NODES_PWD
          volumeMounts:
            - name: vnc-storage
              mountPath: /mnt/qnap
            - name: init-vnc
              mountPath: /vnc-script
          resources:
            limits:
              gpu.intel.com/i915: '1'
          command:
            - /bin/bash
            - -c
            - |
              /vnc-script/init.sh
              /init
      volumes:
        - name: vnc-storage
          persistentVolumeClaim:
            claimName: {{ include "vnc.fullname" . }}-pvc
        - name: init-vnc
          configMap:
            name: init-vnc
            defaultMode: 0755