apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vnc-credentials
spec:
  secretStoreRef:
    name: vnc-secret-store
  data:
  - secretKey: VNC_PASSWORD
    remoteRef:
      key: VNC_PASSWORD
  - secretKey: GITHUB_TOKEN_RAW
    remoteRef:
      key: GITHUB_TOKEN_RAW
  - secretKey: LOCAL_NODES_PWD
    remoteRef:
      key: LOCAL_NODES_PWD
  target:
    name: {{ .Values.existingSecret }}