apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vnc-credentials
spec:
  secretStoreRef:
    name: vnc-secret-store
  data:
  - secretKey: VNC_PASSWORD
    remoteRef:
      key: VNC_PASSWORD
  target:
    name: {{ .Values.existingSecret }}