{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vnc.fullname" . }}-pvc
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dlink
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vnc.fullname" . }}-home-pvc
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dlink-home
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vnc.fullname" . }}-mozilla
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dlink-mozilla
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}