{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vnc.fullname" . }}-pvc
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: qnap
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
{{- end }}