apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vnc.fullname" . }}
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "vnc.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "vnc.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.vncServer.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
            #- name: vnc
            #  containerPort: 5900
          env:
            - name: USER
              value: "{{ .Values.env.USER }}"
            - name: RESOLUTION
              value: "{{ .Values.env.RESOLUTION }}"
            - name: VNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: VNC_PASSWORD
            - name: HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: HTTP_PASSWORD
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: PASSWORD