apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vnc.fullname" . }}
  labels:
{{ include "vnc.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "vnc.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "vnc.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.vncServer.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 5901
          - containerPort: 6901
          env:
            - name: VNC_COL_DEPTH
              value: "24"
            - name: USER
              value: "{{ .Values.env.USER }}"
            - name: VNC_RESOLUTION
              value: "{{ .Values.env.RESOLUTION }}"
            - name: VNC_PW
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: PASSWORD
            #- name: HTTP_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: {{ .Values.existingSecret }}
            #      key: HTTP_PASSWORD
            #- name: PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: {{ .Values.existingSecret }}
            #      key: PASSWORD
          volumeMounts:
            - name: vnc-storage
              mountPath: /mnt/dlink
            - name: vnc-home-storage  # New volume mount
              mountPath: /home/rmikl
              subPath: k8s-tools-config/vnc/home/rmikl
      volumes:
        - name: vnc-storage
          persistentVolumeClaim:
            claimName: {{ include "vnc.fullname" . }}-pvc
        - name: vnc-home-storage 
          persistentVolumeClaim:
            claimName: {{ include "vnc.fullname" . }}-home-pvc