apiVersion: v1
kind: Service
metadata:
  name: vnc-http
  labels:
    {{- include "vnc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "vnc.selectorLabels" . | indent 4 }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: 5901
    - port: 6901
      targetPort: 6901
