apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-user: {{ "admin" | b64enc }} 
  admin-password: {{ randAlphaNum 16 | b64enc  }}
