apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.pod.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"  # Specify the cron schedule here
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            beta.kubernetes.io/arch: amd64
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
            - name: kubectl
              image: {{ .Values.pod.image }}
              command:
                {{- toYaml .Values.pod.command | nindent 16 }}
              resources:
                limits:
                  cpu: {{ .Values.pod.resources.limits.cpu }}
                  memory: {{ .Values.pod.resources.limits.memory }}
                requests:
                  cpu: {{ .Values.pod.resources.requests.cpu }}
                  memory: {{ .Values.pod.resources.requests.memory }}
              env:
                - name: INTERVAL_TIME
                  value: "{{ .Values.pod.env.INTERVAL_TIME }}"
                - name: POOL_NAME
                  value: "{{ .Values.pod.env.POOL_NAME }}"
                - name: POOL_NAMESPACE
                  value: "{{ .Values.pod.env.POOL_NAMESPACE }}"
          restartPolicy: Never
  successfulJobsHistoryLimit: 3  # Keeps history of successful jobs
  failedJobsHistoryLimit: 1  # Keeps history of failed jobs